### ISSUE TITLE
Getting error after train

### ISSUE THREAD

**Issue by kerberosargos** [pbcquoc/vietocr#126]
Hello I have trained my own data by applied [this ](https://github.com/pbcquoc/vietocr/blob/master/vietocr_gettingstart.ipynb) instructions

But my train process could not complete. Error is as following. Do you have any idea?

```
......
iter: 019800 - train loss: 0.458 - lr: 9.17e-08 - load time: 6.57 - gpu time: 485.75
iter: 020000 - train loss: 0.458 - lr: 1.20e-09 - load time: 6.68 - gpu time: 2239.40
can't invoke "event" command: application has been destroyed
    while executing
"event generate $w <<ThemeChanged>>"
"ttk::ThemeChanged"
can't invoke "event" command: application has been destroyed
    while executing
"event generate $w <<ThemeChanged>>"
    (procedure "ttk::ThemeChanged" line 6)
    invoked from within
"ttk::ThemeChanged"
```

my config details as following

```
aug:
  image_aug: true
  masked_language_model: true
backbone: vgg19_bn
cnn:
  hidden: 256
  ks:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
  pretrained: true
  ss:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
dataloader:
  num_workers: 0
  pin_memory: false
dataset:
  data_root: ./dataset/vietocr/
  image_height: 32
  image_max_width: 512
  image_min_width: 32
  name: tr
  train_annotation: train_line_annotation.txt
  valid_annotation: test_line_annotation.txt
device: cpu
optimizer:
  max_lr: 0.0003
  pct_start: 0.1
predictor:
  beamsearch: false
pretrain: https://vocr.vn/data/vietocr/vgg_transformer.pth
quiet: false
seq_modeling: transformer
trainer:
  batch_size: 32
  checkpoint: ./checkpoint/transformerocr_checkpoint.pth
  export: ./weights/transformerocr.pth
  iters: 20000
  log: ./train.log
  metrics: 10000
  print_every: 200
  valid_every: 3000
transformer:
  d_model: 256
  dim_feedforward: 2048
  max_seq_length: 1024
  nhead: 8
  num_decoder_layers: 6
  num_encoder_layers: 6
  pos_dropout: 0.1
  trans_dropout: 0.1
vocab: 'aAbBcCçÇdDeEfFgGğĞhHıIiİjJkKlLmMnNoOöÖpPqQrRsSşŞtTuUüÜvVwWxXyYzZ0123456789!"#€$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
weights: https://vocr.vn/data/vietocr/vgg_transformer.pth
weights_dir: ./weights/
```

Thank you for your support in advance.
